services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment: { POSTGRES_DB: klaxon, POSTGRES_USER: klaxon, POSTGRES_PASSWORD: klaxon }
    env_file:
      - .env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
  app:
    image: klaxon:${DOCKER_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
    restart: unless-stopped
    environment: { DATABASE_URL: ecto://klaxon:klaxon@db/klaxon }
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./.local
        target: /var/local/klaxon
        read_only: true
    links:
      - db
    ports: [ "127.0.0.1:${KLAXON_PORT:-4000}:4000" ]

volumes:
  dbdata:
