services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: klaxon
      POSTGRES_USER: klaxon
    env_file:
      - .env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./.local
        target: /var/local/klaxon
    ports: [ "127.0.0.1:${POSTGRES_PORT:-54320}:5432" ]

  app:
    image: klaxon
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: ecto://klaxon:${POSTGRES_PASSWORD}@db/klaxon
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./.local
        target: /var/local/klaxon
    links:
      - db
    ports: [ "127.0.0.1:${KLAXON_PORT:-4000}:4000" ]

volumes:
  dbdata:
